@hostname = localhost
@port = 7033
@host = {{hostname}}:{{port}}
@base = https://{{host}}
@contentType = application/json

###

POST {{base}}/people/addperson
Content-Type:{{contentType}}

{
	"FirstName": "Dan",
	"LastName": "Barrera",
	"Age": 21,
	"PersonalStatement": "Test Statement",
	"Skills": [
		"Skill 1",
		"Skill 2",
		"Skill 3",
		"Skill 4",
		"Skill 5"
	],
	"Address": {
		"StreetNumber": 0,
		"Unit": "123",
		"StreetName": "Roadside",
		"City": "General Luna",
		"State": "None",
		"PostalCode": "8419",
		"Country": "Philippines",
		"GeoLoc": {
			"Longitude": 1234.1234,
			"Latitude": 4312.4312
		}
	}
}

###

###GET {{base}}/people/filterAge

 
